### ISSUE TITLE
Slogan idea 

### ISSUE THREAD

**Issue by esmaydogdu** [findmentor-network/find-mentor#274]
...findmentor...
sharpens your mind
eases your loneliness

**Comment by mmertdogann** [comment]
Findmentor - Programming for Everyone

**Comment by muratdemirci** [comment]
"If you cannot see where you are going,
 ask someone who has been there before." 
                                            — _J Loren Norris_

**Comment by ahmetcanaydemir** [comment]
I think we can convert this issue to a discussion. [discussions/ideas](https://github.com/findmentor-network/find-mentor/discussions/categories/ideas)

**Comment by cagataycali** [comment]
Great idea @ahmetcanaydemir.
I created a discussion, let's dive from there.
https://github.com/findmentor-network/find-mentor/discussions/275
